//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investing.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public System.Guid Id { get; set; }
        public System.Guid ExchangeId { get; set; }
        public string CompanyName { get; set; }
        public string Symbol { get; set; }
        public string IPOYear { get; set; }
        public Nullable<System.Guid> SectorId { get; set; }
        public Nullable<System.Guid> IndustryId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Exchange Exchange { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
